version: '3.1'

services:
  db:
    image: postgres:14.2-alpine
    container_name: docker-health-plan
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: health_plan
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: